#!/bin/bash
#
# Applies setup.
#
set -o nounset -o errexit -o pipefail

# Settings
REPO_NAME="fedora-setup"
REPO_URL="git@github.com:fernandoacorreia/$REPO_NAME.git"
REPO_DIR="$HOME/$REPO_NAME"

missing_executable() {
  local executable=$1
  ! [ -x "$(command -v ${executable})" ]
}

install_git() {
  if missing_executable git
  then
    echo "Installing git"
    sudo dnf install git-all
  fi
}

# Create ssh key
create_ssh_key() {
  if ! test -f $HOME/.ssh/id_rsa
  then
    echo "Creating ssh key"
    ssh-keygen -t rsa -b 4096
    echo "New ssh key created:"
    cat $HOME/.ssh/id_rsa.pub
    echo "Add it to your GitHub account and run this script again."
    echo "See https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/"
    exit 1
  fi
}

add_ssh_key_to_agent() {
  echo "Adding ssh key to ssh agent"
  eval "$(ssh-agent -s)"
  ssh-add $HOME/.ssh/id_rsa
}

clone_repository() {
  if ! test -d "$REPO_DIR"
  then
    echo "Cloning from $REPO_URL"
    cd $HOME
    git clone --recurse-submodules $REPO_URL $REPO_NAME
  fi
}

install_ansible() {
  if missing_executable ansible-playbook; then
    echo "Installing Ansible"
    sudo dnf install python3-pip
    sudo pip3 install ansible
  fi
}

apply_playbook() {
  echo "Applying Ansible playbook"
  cd "$REPO_DIR/ansible"
  export ANSIBLE_NOCOWS=1
  ansible-playbook -i inventory --ask-become-pass playbook.yml
}

install_git
create_ssh_key
add_ssh_key_to_agent
clone_repository
install_ansible
apply_playbook
echo "Setup finished"
