---
- name: Create link for ~/.config/nvim/
  file:
    src: "{{ setup_dir }}/nvim/"
    dest: "{{ home_dir }}/.config/nvim"
    state: link

- name: Install neovim
  become: yes
  dnf:
    name: neovim
    state: latest

- name: Set neovim as alternative to vi
  become: yes
  alternatives:
    name: vi
    link: /usr/local/bin/vi
    path: /usr/bin/nvim

- name: Set neovim as alternative to vim
  become: yes
  alternatives:
    name: vim
    link: /usr/local/bin/vim
    path: /usr/bin/nvim
