---
# Based on https://docs.docker.com/engine/install/fedora/#install-using-the-repository

- name: Add Docker repository
  become: yes
  command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
  args:
    creates: "/etc/yum.repos.d/docker-ce.repo"
    warn: false

- name: Install Docker
  become: yes
  dnf:
    enablerepo: docker-ce
    update_cache: yes
    state: latest
    name:
    - containerd.io
    - docker-ce
    - docker-ce-cli

- name: Start Docker service
  become: yes
  systemd:
    enabled: yes
    state: started
    name: docker

- name: Add user to docker group
  become: yes
  user:
    name: '{{ ansible_user_id }}'
    groups: docker
    append: yes
