---
- hosts: all

  vars:
    hack_font_version: "v3.003"
    node_version: "12.11.0"

  roles:
  - common
  - chrome
#  - docker
#  - docker-compose
#  - java
#  - zsh
#  - lnav
#  - homefiles
#  - ripgrep
#  - fzf
#  - neovim
